CREATE OR REPLACE PROCEDURE TEST4 IS
BEGIN
    INSERT INTO TBL_TEST VALUES(1, 'TEST1', 100); 
    INSERT INTO TBL_TEST VALUES(2, 'TEST2', 200);
    INSERT INTO TBL_TEST VALUES(3, 'TEST3', 300);
    INSERT INTO TBL_TEST VALUES(4, 'TEST4', 400);
    COMMIT;
END;
/
show errors
