CREATE OR REPLACE PROCEDURE TEST6 IS
BEGIN
    FOR I IN REVERSE 10..15
    LOOP
        INSERT INTO TBL_TEST VALUES(I, 'TEST' || TO_CHAR(I), I * 100);
    END LOOP;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
show errors
